import type { Locale } from "@/lib/i18n";

export const GUIDE_UI_COPY = {
  pl: {
    indexTitle: "Przewodniki po zakupie mieszkania",
    indexIntro: "Praktyczne materiały o cenie, lokalizacji, dokumentach, kredycie i ryzykach zakupu.",
    areas: "Osiedla",
    check: "Sprawdź mieszkanie",
    read: "Czytaj",
    polishNotice: "Materiały redakcyjne są obecnie publikowane po polsku.",
    back: "Przewodniki",
    report: "Pełny raport",
    keyPoints: "Najważniejsze",
    nextChecks: "Co sprawdzić dalej",
    relatedAreas: "Aktualne dane powiązanych osiedli",
    moreGuides: "Więcej przewodników",
    checkSpecific: "Sprawdź konkretne mieszkanie",
    author: "Autor",
    reviewer: "Recenzja",
    updated: "Aktualizacja",
    reviewScope: "Zakres weryfikacji",
    sources: "Źródła wykorzystane w materiale",
    sourceSupports: "Zakres źródła",
    editorialInfo: "Informacje redakcyjne",
    articleLanguage: "Język materiału: polski",
    disclaimer: {
      market: "Materiał wyjaśnia sposób analizy rynku. Nie jest wyceną konkretnego mieszkania ani rekomendacją zakupu.",
      financial: "Materiał ma charakter informacyjny. Nie jest poradą inwestycyjną, kredytową ani podatkową i nie gwarantuje wyniku finansowego.",
      legal: "Materiał ma charakter informacyjny. Nie jest poradą prawną ani interpretacją dokumentów konkretnej nieruchomości.",
    },
    areasLoading: "Pobieramy aktualne dane osiedli...",
    areasError: "Nie udało się pobrać aktualnych danych osiedli.",
    areasPartial: "Część danych jest niedostępna. Nie zastępujemy jej wartościami statycznymi.",
    retry: "Spróbuj ponownie",
    noPrice: "Brak wiarygodnej mediany ceny",
    transaction: "cena transakcyjna",
    listing: "cena ofertowa",
    demo: "dane demonstracyjne",
    source: "Źródło",
    sourceUnknown: "źródło niepodane",
    sourceUpdated: "aktualizacja",
  },
  en: {
    indexTitle: "Apartment buying guides",
    indexIntro: "Practical material about price, location, documents, mortgages and purchase risks.",
    areas: "Neighborhoods",
    check: "Check an apartment",
    read: "Read",
    polishNotice: "Editorial articles are currently published in Polish.",
    back: "Guides",
    report: "Full report",
    keyPoints: "Key points",
    nextChecks: "What to check next",
    relatedAreas: "Current data for related neighborhoods",
    moreGuides: "More guides",
    checkSpecific: "Check a specific apartment",
    author: "Author",
    reviewer: "Review",
    updated: "Updated",
    reviewScope: "Review scope",
    sources: "Sources used in this article",
    sourceSupports: "Source scope",
    editorialInfo: "Editorial information",
    articleLanguage: "Article language: Polish",
    disclaimer: {
      market: "This material explains a market-analysis method. It is not a valuation of a specific apartment or a purchase recommendation.",
      financial: "This material is informational. It is not investment, credit or tax advice and does not guarantee a financial outcome.",
      legal: "This material is informational. It is not legal advice or an interpretation of documents for a specific property.",
    },
    areasLoading: "Fetching current neighborhood data...",
    areasError: "Current neighborhood data could not be loaded.",
    areasPartial: "Some data is unavailable. It is not replaced with static values.",
    retry: "Try again",
    noPrice: "Reliable median price unavailable",
    transaction: "transaction price",
    listing: "asking price",
    demo: "demo data",
    source: "Source",
    sourceUnknown: "source not supplied",
    sourceUpdated: "updated",
  },
  ru: {
    indexTitle: "Гайды по покупке квартиры",
    indexIntro: "Практические материалы о цене, районе, документах, ипотеке и рисках покупки.",
    areas: "Районы",
    check: "Проверить квартиру",
    read: "Читать",
    polishNotice: "Редакционные материалы сейчас публикуются на польском языке.",
    back: "Гайды",
    report: "Полный отчёт",
    keyPoints: "Главное",
    nextChecks: "Что проверить дальше",
    relatedAreas: "Актуальные данные связанных районов",
    moreGuides: "Другие гайды",
    checkSpecific: "Проверить конкретную квартиру",
    author: "Автор",
    reviewer: "Рецензия",
    updated: "Обновлено",
    reviewScope: "Объём проверки",
    sources: "Источники материала",
    sourceSupports: "Что подтверждает источник",
    editorialInfo: "Редакционная информация",
    articleLanguage: "Язык материала: польский",
    disclaimer: {
      market: "Материал объясняет метод анализа рынка. Это не оценка конкретной квартиры и не рекомендация покупки.",
      financial: "Материал носит информационный характер. Это не инвестиционная, кредитная или налоговая консультация и не гарантия финансового результата.",
      legal: "Материал носит информационный характер. Это не юридическая консультация и не толкование документов конкретного объекта.",
    },
    areasLoading: "Загружаем актуальные данные районов...",
    areasError: "Не удалось загрузить актуальные данные районов.",
    areasPartial: "Часть данных недоступна. Мы не заменяем её статическими значениями.",
    retry: "Повторить",
    noPrice: "Надёжная медиана цены отсутствует",
    transaction: "цена сделки",
    listing: "цена предложения",
    demo: "демонстрационные данные",
    source: "Источник",
    sourceUnknown: "источник не указан",
    sourceUpdated: "обновлено",
  },
  uk: {
    indexTitle: "Гайди з купівлі квартири",
    indexIntro: "Практичні матеріали про ціну, район, документи, іпотеку та ризики купівлі.",
    areas: "Райони",
    check: "Перевірити квартиру",
    read: "Читати",
    polishNotice: "Редакційні матеріали зараз публікуються польською мовою.",
    back: "Гайди",
    report: "Повний звіт",
    keyPoints: "Головне",
    nextChecks: "Що перевірити далі",
    relatedAreas: "Актуальні дані пов'язаних районів",
    moreGuides: "Інші гайди",
    checkSpecific: "Перевірити конкретну квартиру",
    author: "Автор",
    reviewer: "Рецензія",
    updated: "Оновлено",
    reviewScope: "Обсяг перевірки",
    sources: "Джерела матеріалу",
    sourceSupports: "Що підтверджує джерело",
    editorialInfo: "Редакційна інформація",
    articleLanguage: "Мова матеріалу: польська",
    disclaimer: {
      market: "Матеріал пояснює метод аналізу ринку. Це не оцінка конкретної квартири й не рекомендація купівлі.",
      financial: "Матеріал має інформаційний характер. Це не інвестиційна, кредитна чи податкова консультація і не гарантія фінансового результату.",
      legal: "Матеріал має інформаційний характер. Це не юридична консультація й не тлумачення документів конкретного об'єкта.",
    },
    areasLoading: "Завантажуємо актуальні дані районів...",
    areasError: "Не вдалося завантажити актуальні дані районів.",
    areasPartial: "Частина даних недоступна. Ми не замінюємо її статичними значеннями.",
    retry: "Повторити",
    noPrice: "Надійної медіани ціни немає",
    transaction: "ціна угоди",
    listing: "ціна пропозиції",
    demo: "демонстраційні дані",
    source: "Джерело",
    sourceUnknown: "джерело не вказано",
    sourceUpdated: "оновлено",
  },
} as const satisfies Record<Locale, object>;

const CATEGORY_COPY: Record<Locale, Record<string, string>> = {
  pl: {},
  en: { Rynek: "Market", Dzielnice: "Neighborhoods", "Okolice miasta": "Metro area", Inwestycja: "Investment", Finanse: "Finance", "Lista kontroli": "Checklist", Prawo: "Legal" },
  ru: { Rynek: "Рынок", Dzielnice: "Районы", "Okolice miasta": "Пригороды", Inwestycja: "Инвестиции", Finanse: "Финансы", "Lista kontroli": "Чек-лист", Prawo: "Право" },
  uk: { Rynek: "Ринок", Dzielnice: "Райони", "Okolice miasta": "Передмістя", Inwestycja: "Інвестиції", Finanse: "Фінанси", "Lista kontroli": "Чекліст", Prawo: "Право" },
};

export function guideCategory(category: string, locale: Locale) {
  return CATEGORY_COPY[locale][category] ?? category;
}
