import type { PropertyScores, ScoreCode, ScoreDimensionExplainability } from "@/lib/api";
import { DEFAULT_LOCALE, type Locale } from "@/lib/i18n";

const LABELS: Record<Locale, Record<string, string>> = {
  en: {
    unknown: "Unavailable",
    strong_candidate: "Strong candidate",
    good_option: "Good option",
    fair_option: "Fair option",
    overpriced: "Looks expensive",
    risky: "High risk",
    weak_fit: "Weak fit",
    below_fair: "Below fair price",
    fair: "In fair range",
    above_fair: "Above fair price",
    low_risk: "Low risk",
    moderate_risk: "Moderate risk",
    elevated_risk: "Elevated risk",
    high_risk: "High risk",
    weak_negotiation: "Weak negotiation",
    some_negotiation: "Some negotiation",
    negotiable: "Negotiable",
    strong_negotiation: "Strong negotiation",
    weak: "Weak",
    moderate: "Moderate",
    good: "Good",
    strong: "Strong",
  },
  pl: {
    unknown: "Brak danych",
    strong_candidate: "Mocny kandydat",
    good_option: "Dobra opcja",
    fair_option: "Rozsądna opcja",
    overpriced: "Wygląda drogo",
    risky: "Wysokie ryzyko",
    weak_fit: "Słabe dopasowanie",
    below_fair: "Poniżej ceny rynkowej",
    fair: "W zakresie rynkowym",
    above_fair: "Powyżej ceny rynkowej",
    low_risk: "Niskie ryzyko",
    moderate_risk: "Umiarkowane ryzyko",
    elevated_risk: "Podwyższone ryzyko",
    high_risk: "Wysokie ryzyko",
    weak_negotiation: "Słaby potencjał negocjacji",
    some_negotiation: "Jest miejsce na negocjacje",
    negotiable: "Warto negocjować",
    strong_negotiation: "Silny potencjał negocjacji",
    weak: "Słaby",
    moderate: "Średni",
    good: "Dobry",
    strong: "Silny",
  },
  ru: {
    unknown: "Нет данных",
    strong_candidate: "Сильный кандидат",
    good_option: "Хороший вариант",
    fair_option: "Нормальный вариант",
    overpriced: "Похоже дорого",
    risky: "Высокий риск",
    weak_fit: "Слабое совпадение",
    below_fair: "Ниже рыночной оценки",
    fair: "В рыночном диапазоне",
    above_fair: "Выше рыночной оценки",
    low_risk: "Низкий риск",
    moderate_risk: "Умеренный риск",
    elevated_risk: "Повышенный риск",
    high_risk: "Высокий риск",
    weak_negotiation: "Слабый торг",
    some_negotiation: "Есть торг",
    negotiable: "Торг уместен",
    strong_negotiation: "Сильный торг",
    weak: "Слабый",
    moderate: "Средний",
    good: "Хороший",
    strong: "Сильный",
  },
  uk: {
    unknown: "Немає даних",
    strong_candidate: "Сильний кандидат",
    good_option: "Хороший варіант",
    fair_option: "Нормальний варіант",
    overpriced: "Схоже дорого",
    risky: "Високий ризик",
    weak_fit: "Слабка відповідність",
    below_fair: "Нижче ринкової оцінки",
    fair: "У ринковому діапазоні",
    above_fair: "Вище ринкової оцінки",
    low_risk: "Низький ризик",
    moderate_risk: "Помірний ризик",
    elevated_risk: "Підвищений ризик",
    high_risk: "Високий ризик",
    weak_negotiation: "Слабкий торг",
    some_negotiation: "Є простір для торгу",
    negotiable: "Торг доречний",
    strong_negotiation: "Сильний торг",
    weak: "Слабкий",
    moderate: "Середній",
    good: "Хороший",
    strong: "Сильний",
  },
};

const DRIVER_LABELS: Record<Locale, Record<string, string>> = {
  en: {
    price_position_supportive: "the price position supports the result",
    price_position_unfavorable: "the price position weakens the result",
    area_trend_supportive: "the local price trend supports the result",
    area_trend_weak: "the local price trend weakens the result",
    transport_access_strong: "public transport access is strong",
    transport_access_weak: "public transport access is weak",
    liquidity_signal_strong: "local resale liquidity looks strong",
    liquidity_signal_weak: "local resale liquidity looks weak",
    rental_signal_strong: "the observed rental signal is strong",
    rental_signal_weak: "the observed rental signal is weak",
    risk_burden_low: "the combined risk burden is low",
    risk_burden_high: "the combined risk burden is high",
    data_quality_strong: "property data coverage is strong",
    data_quality_weak: "property data coverage is weak",
    price_risk_low: "the asking price creates limited price risk",
    price_risk_high: "the asking price creates elevated price risk",
    market_risk_low: "market exposure signals limited risk",
    market_risk_high: "market exposure signals elevated risk",
    location_risk_low: "available surroundings data indicates limited risk",
    location_risk_high: "available surroundings data indicates elevated risk",
    building_risk_low: "available building details indicate limited risk",
    building_risk_high: "available building details indicate elevated risk",
    data_risk_low: "the analysis has good input coverage",
    data_risk_high: "missing or weak inputs increase uncertainty",
    price_premium_leverage: "the price premium supports negotiation",
    price_position_limits_leverage: "the current price limits negotiation leverage",
    long_market_exposure: "long market exposure supports negotiation",
    fresh_market_entry: "a recent market entry limits negotiation leverage",
    price_reduction_history: "previous price reductions support negotiation",
    relisted_listing: "relisting supports negotiation",
    buyer_supply_leverage: "growing local supply supports the buyer",
    seller_supply_leverage: "limited local supply supports the seller",
    short_area_market_exposure: "similar properties leave the market relatively quickly",
    long_area_market_exposure: "similar properties remain on the market longer",
    demand_exceeds_new_supply: "removals exceed new local supply",
    new_supply_exceeds_removals: "new local supply exceeds removals",
    rental_evidence_strong: "the rental estimate has a strong comparable sample",
    rental_evidence_limited: "the rental comparable sample is limited",
    rental_yield_signal_strong: "the observed rent supports a stronger gross-yield signal",
    rental_yield_signal_weak: "the observed rent supports a weaker gross-yield signal",
    missing_nearest_stop_m: "public transport distance is unavailable",
    missing_planned_investments_within_2km: "nearby planned investments are unavailable",
    missing_listing_market_metrics: "local listing-market history is unavailable",
    missing_lifestyle_infrastructure: "school and green-space coverage is incomplete",
    missing_rental_observations: "independent rental observations are insufficient",
    missing_market_evidence: "transaction and comparable evidence is insufficient",
    missing_nearest_major_road_m: "major-road proximity is unavailable",
    missing_nearest_industrial_zone_m: "industrial-zone proximity is unavailable",
    missing_floor: "the apartment floor is unavailable",
    missing_building_floors: "the number of building floors is unavailable",
    missing_building_year: "the building year is unavailable",
  },
  pl: {
    price_position_supportive: "pozycja ceny wspiera wynik",
    price_position_unfavorable: "pozycja ceny osłabia wynik",
    area_trend_supportive: "lokalny trend cenowy wspiera wynik",
    area_trend_weak: "lokalny trend cenowy osłabia wynik",
    transport_access_strong: "dostęp do transportu publicznego jest dobry",
    transport_access_weak: "dostęp do transportu publicznego jest słaby",
    liquidity_signal_strong: "lokalna płynność odsprzedaży wygląda dobrze",
    liquidity_signal_weak: "lokalna płynność odsprzedaży wygląda słabo",
    rental_signal_strong: "obserwowany sygnał najmu jest mocny",
    rental_signal_weak: "obserwowany sygnał najmu jest słaby",
    risk_burden_low: "łączny poziom ryzyka jest niski",
    risk_burden_high: "łączny poziom ryzyka jest wysoki",
    data_quality_strong: "pokrycie danych mieszkania jest dobre",
    data_quality_weak: "pokrycie danych mieszkania jest słabe",
    price_risk_low: "cena ofertowa tworzy niewielkie ryzyko cenowe",
    price_risk_high: "cena ofertowa tworzy podwyższone ryzyko cenowe",
    market_risk_low: "czas i historia oferty wskazują na niewielkie ryzyko",
    market_risk_high: "czas i historia oferty wskazują na podwyższone ryzyko",
    location_risk_low: "dostępne dane o otoczeniu wskazują na niewielkie ryzyko",
    location_risk_high: "dostępne dane o otoczeniu wskazują na podwyższone ryzyko",
    building_risk_low: "dostępne dane budynku wskazują na niewielkie ryzyko",
    building_risk_high: "dostępne dane budynku wskazują na podwyższone ryzyko",
    data_risk_low: "analiza ma dobre pokrycie danych wejściowych",
    data_risk_high: "braki danych zwiększają niepewność",
    price_premium_leverage: "premia cenowa wspiera negocjacje",
    price_position_limits_leverage: "obecna cena ogranicza siłę negocjacji",
    long_market_exposure: "długi czas oferty wspiera negocjacje",
    fresh_market_entry: "krótki czas oferty ogranicza siłę negocjacji",
    price_reduction_history: "wcześniejsze obniżki wspierają negocjacje",
    relisted_listing: "ponowne wystawienie wspiera negocjacje",
    buyer_supply_leverage: "rosnąca lokalna podaż wspiera kupującego",
    seller_supply_leverage: "ograniczona lokalna podaż wspiera sprzedającego",
    short_area_market_exposure: "podobne oferty relatywnie szybko znikają z rynku",
    long_area_market_exposure: "podobne oferty dłużej pozostają na rynku",
    demand_exceeds_new_supply: "ubywa więcej ofert, niż pojawia się nowych",
    new_supply_exceeds_removals: "nowych ofert jest więcej niż usuniętych",
    rental_evidence_strong: "szacunek najmu ma mocną próbę porównawczą",
    rental_evidence_limited: "próba porównawcza najmu jest ograniczona",
    rental_yield_signal_strong: "obserwowany najem wspiera wyższy sygnał rentowności brutto",
    rental_yield_signal_weak: "obserwowany najem wspiera niższy sygnał rentowności brutto",
    missing_nearest_stop_m: "brakuje odległości do transportu publicznego",
    missing_planned_investments_within_2km: "brakuje danych o planowanych inwestycjach",
    missing_listing_market_metrics: "brakuje historii lokalnego rynku ofert",
    missing_lifestyle_infrastructure: "dane o szkołach i zieleni są niepełne",
    missing_rental_observations: "brakuje wystarczających niezależnych obserwacji najmu",
    missing_market_evidence: "brakuje wystarczających transakcji i ofert porównawczych",
    missing_nearest_major_road_m: "brakuje odległości od głównej drogi",
    missing_nearest_industrial_zone_m: "brakuje odległości od strefy przemysłowej",
    missing_floor: "brakuje piętra mieszkania",
    missing_building_floors: "brakuje liczby pięter budynku",
    missing_building_year: "brakuje roku budowy",
  },
  ru: {
    price_position_supportive: "положение цены поддерживает результат",
    price_position_unfavorable: "положение цены ухудшает результат",
    area_trend_supportive: "локальный ценовой тренд поддерживает результат",
    area_trend_weak: "локальный ценовой тренд ухудшает результат",
    transport_access_strong: "доступ к общественному транспорту хороший",
    transport_access_weak: "доступ к общественному транспорту слабый",
    liquidity_signal_strong: "локальная ликвидность перепродажи выглядит высокой",
    liquidity_signal_weak: "локальная ликвидность перепродажи выглядит низкой",
    rental_signal_strong: "наблюдаемый арендный сигнал высокий",
    rental_signal_weak: "наблюдаемый арендный сигнал низкий",
    risk_burden_low: "совокупный уровень риска низкий",
    risk_burden_high: "совокупный уровень риска высокий",
    data_quality_strong: "покрытие данных квартиры хорошее",
    data_quality_weak: "покрытие данных квартиры слабое",
    price_risk_low: "цена предложения создаёт небольшой ценовой риск",
    price_risk_high: "цена предложения создаёт повышенный ценовой риск",
    market_risk_low: "срок и история объявления указывают на небольшой риск",
    market_risk_high: "срок и история объявления указывают на повышенный риск",
    location_risk_low: "доступные данные об окружении указывают на небольшой риск",
    location_risk_high: "доступные данные об окружении указывают на повышенный риск",
    building_risk_low: "доступные данные о здании указывают на небольшой риск",
    building_risk_high: "доступные данные о здании указывают на повышенный риск",
    data_risk_low: "анализ имеет хорошее покрытие исходных данных",
    data_risk_high: "пробелы в данных увеличивают неопределённость",
    price_premium_leverage: "ценовая премия усиливает переговорную позицию",
    price_position_limits_leverage: "текущая цена ограничивает переговорную позицию",
    long_market_exposure: "долгое размещение усиливает переговорную позицию",
    fresh_market_entry: "недавнее размещение ограничивает переговорную позицию",
    price_reduction_history: "предыдущие снижения цены поддерживают переговоры",
    relisted_listing: "повторное размещение поддерживает переговоры",
    buyer_supply_leverage: "рост локального предложения поддерживает покупателя",
    seller_supply_leverage: "ограниченное предложение поддерживает продавца",
    short_area_market_exposure: "похожие объекты относительно быстро уходят с рынка",
    long_area_market_exposure: "похожие объекты дольше остаются на рынке",
    demand_exceeds_new_supply: "снятых предложений больше, чем новых",
    new_supply_exceeds_removals: "новых предложений больше, чем снятых",
    rental_evidence_strong: "оценка аренды основана на хорошей выборке аналогов",
    rental_evidence_limited: "выборка арендных аналогов ограничена",
    rental_yield_signal_strong: "наблюдаемая аренда поддерживает более высокую валовую доходность",
    rental_yield_signal_weak: "наблюдаемая аренда поддерживает более низкую валовую доходность",
    missing_nearest_stop_m: "нет расстояния до общественного транспорта",
    missing_planned_investments_within_2km: "нет данных о запланированных проектах",
    missing_listing_market_metrics: "нет истории локального рынка объявлений",
    missing_lifestyle_infrastructure: "данные о школах и зелёных зонах неполные",
    missing_rental_observations: "недостаточно независимых наблюдений аренды",
    missing_market_evidence: "недостаточно транзакций и сопоставимых предложений",
    missing_nearest_major_road_m: "нет расстояния до крупной дороги",
    missing_nearest_industrial_zone_m: "нет расстояния до промышленной зоны",
    missing_floor: "нет этажа квартиры",
    missing_building_floors: "нет этажности здания",
    missing_building_year: "нет года постройки",
  },
  uk: {
    price_position_supportive: "позиція ціни підтримує результат",
    price_position_unfavorable: "позиція ціни погіршує результат",
    area_trend_supportive: "локальний ціновий тренд підтримує результат",
    area_trend_weak: "локальний ціновий тренд погіршує результат",
    transport_access_strong: "доступ до громадського транспорту добрий",
    transport_access_weak: "доступ до громадського транспорту слабкий",
    liquidity_signal_strong: "локальна ліквідність перепродажу виглядає високою",
    liquidity_signal_weak: "локальна ліквідність перепродажу виглядає низькою",
    rental_signal_strong: "спостережуваний сигнал оренди високий",
    rental_signal_weak: "спостережуваний сигнал оренди низький",
    risk_burden_low: "сукупний рівень ризику низький",
    risk_burden_high: "сукупний рівень ризику високий",
    data_quality_strong: "покриття даних квартири добре",
    data_quality_weak: "покриття даних квартири слабке",
    price_risk_low: "ціна пропозиції створює невеликий ціновий ризик",
    price_risk_high: "ціна пропозиції створює підвищений ціновий ризик",
    market_risk_low: "строк та історія оголошення вказують на невеликий ризик",
    market_risk_high: "строк та історія оголошення вказують на підвищений ризик",
    location_risk_low: "наявні дані про оточення вказують на невеликий ризик",
    location_risk_high: "наявні дані про оточення вказують на підвищений ризик",
    building_risk_low: "наявні дані про будинок вказують на невеликий ризик",
    building_risk_high: "наявні дані про будинок вказують на підвищений ризик",
    data_risk_low: "аналіз має добре покриття вхідних даних",
    data_risk_high: "прогалини в даних збільшують невизначеність",
    price_premium_leverage: "цінова премія посилює переговорну позицію",
    price_position_limits_leverage: "поточна ціна обмежує переговорну позицію",
    long_market_exposure: "тривале розміщення посилює переговорну позицію",
    fresh_market_entry: "недавнє розміщення обмежує переговорну позицію",
    price_reduction_history: "попередні зниження ціни підтримують переговори",
    relisted_listing: "повторне розміщення підтримує переговори",
    buyer_supply_leverage: "зростання локальної пропозиції підтримує покупця",
    seller_supply_leverage: "обмежена пропозиція підтримує продавця",
    short_area_market_exposure: "схожі об'єкти відносно швидко залишають ринок",
    long_area_market_exposure: "схожі об'єкти довше залишаються на ринку",
    demand_exceeds_new_supply: "знятих пропозицій більше, ніж нових",
    new_supply_exceeds_removals: "нових пропозицій більше, ніж знятих",
    rental_evidence_strong: "оцінка оренди має добру вибірку аналогів",
    rental_evidence_limited: "вибірка орендних аналогів обмежена",
    rental_yield_signal_strong: "спостережувана оренда підтримує вищу валову дохідність",
    rental_yield_signal_weak: "спостережувана оренда підтримує нижчу валову дохідність",
    missing_nearest_stop_m: "немає відстані до громадського транспорту",
    missing_planned_investments_within_2km: "немає даних про заплановані проєкти",
    missing_listing_market_metrics: "немає історії локального ринку оголошень",
    missing_lifestyle_infrastructure: "дані про школи та зелені зони неповні",
    missing_rental_observations: "недостатньо незалежних спостережень оренди",
    missing_market_evidence: "недостатньо транзакцій та порівнянних пропозицій",
    missing_nearest_major_road_m: "немає відстані до головної дороги",
    missing_nearest_industrial_zone_m: "немає відстані до промислової зони",
    missing_floor: "немає поверху квартири",
    missing_building_floors: "немає поверховості будинку",
    missing_building_year: "немає року будівництва",
  },
};

export function scoreLabel(value: string, locale: Locale = DEFAULT_LOCALE) {
  return LABELS[locale][value] ?? LABELS[DEFAULT_LOCALE][value] ?? value;
}

export function scoreDimension(
  scores: PropertyScores,
  scoreCode: ScoreCode,
): ScoreDimensionExplainability | undefined {
  return scores.explainability?.score_details?.find((item) => item.score_code === scoreCode);
}

export function scoreDriverLabel(code: string, locale: Locale = DEFAULT_LOCALE) {
  return DRIVER_LABELS[locale][code] ?? DRIVER_LABELS[DEFAULT_LOCALE][code] ?? LABELS[locale].unknown;
}

export function scoreExplanationReasons(
  scores: PropertyScores,
  scoreCode: ScoreCode,
  locale: Locale = DEFAULT_LOCALE,
) {
  return (scoreDimension(scores, scoreCode)?.drivers ?? [])
    .filter((driver) => driver.direction !== "unknown")
    .slice(0, 3)
    .map((driver) => scoreDriverLabel(driver.code, locale));
}

export function decisionTone(scores: PropertyScores) {
  if (scores.decision_label === "risky" || scores.decision_label === "weak_fit") {
    return "warning";
  }
  if (scores.decision_label === "overpriced") {
    return "error";
  }
  return "info";
}
